export type schemaMaid = {
    id: number;
    name: string;
    date_of_birth: string;
    place_of_birth: string;
    height: string;
    weight: string;
    nationality: string;
    religion: string;
    education_level: string;
};

export const dataMaid: schemaMaid[] = [
    {
        id: 1,
        name: 'Siti Aisyah',
        date_of_birth: '1998-03-14',
        place_of_birth: 'Jakarta',
        height: '158',
        weight: '52',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 2,
        name: 'Maria Lopez',
        date_of_birth: '1995-07-22',
        place_of_birth: 'Manila',
        height: '160',
        weight: '55',
        nationality: 'Filipino',
        religion: 'Christian',
        education_level: 'College',
    },
    {
        id: 3,
        name: 'Nguyen Thi Hoa',
        date_of_birth: '2000-01-09',
        place_of_birth: 'Hanoi',
        height: '154',
        weight: '48',
        nationality: 'Vietnamese',
        religion: 'Buddhist',
        education_level: 'High School',
    },
    {
        id: 4,
        name: 'Putri Maharani',
        date_of_birth: '1999-11-02',
        place_of_birth: 'Bandung',
        height: '162',
        weight: '50',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 5,
        name: 'Aye Chan',
        date_of_birth: '1997-05-17',
        place_of_birth: 'Yangon',
        height: '156',
        weight: '49',
        nationality: 'Burmese',
        religion: 'Buddhist',
        education_level: 'Middle School',
    },
    {
        id: 6,
        name: 'Kavita Sharma',
        date_of_birth: '1996-09-25',
        place_of_birth: 'New Delhi',
        height: '159',
        weight: '54',
        nationality: 'Indian',
        religion: 'Hindu',
        education_level: 'College',
    },
    {
        id: 7,
        name: 'Nurul Hidayah',
        date_of_birth: '1998-12-12',
        place_of_birth: 'Surabaya',
        height: '155',
        weight: '50',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 8,
        name: 'Fatimah Zahra',
        date_of_birth: '1995-04-30',
        place_of_birth: 'Medan',
        height: '161',
        weight: '53',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 9,
        name: 'Anjali Kumari',
        date_of_birth: '1997-08-10',
        place_of_birth: 'Bihar',
        height: '157',
        weight: '51',
        nationality: 'Indian',
        religion: 'Hindu',
        education_level: 'High School',
    },
    {
        id: 10,
        name: 'Nguyen Lan',
        date_of_birth: '1999-02-19',
        place_of_birth: 'Ho Chi Minh City',
        height: '153',
        weight: '47',
        nationality: 'Vietnamese',
        religion: 'Buddhist',
        education_level: 'High School',
    },
    {
        id: 11,
        name: 'Rosita Dela Cruz',
        date_of_birth: '1996-06-01',
        place_of_birth: 'Cebu',
        height: '160',
        weight: '54',
        nationality: 'Filipino',
        religion: 'Christian',
        education_level: 'College',
    },
    {
        id: 12,
        name: 'Sri Wahyuni',
        date_of_birth: '1998-10-07',
        place_of_birth: 'Semarang',
        height: '158',
        weight: '52',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 13,
        name: 'Laila Hasan',
        date_of_birth: '2000-12-21',
        place_of_birth: 'Kuala Lumpur',
        height: '157',
        weight: '50',
        nationality: 'Malaysian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 14,
        name: 'Amina Yusuf',
        date_of_birth: '1994-03-03',
        place_of_birth: 'Jakarta',
        height: '163',
        weight: '56',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'College',
    },
    {
        id: 15,
        name: 'Mei Ling',
        date_of_birth: '1997-07-15',
        place_of_birth: 'Guangzhou',
        height: '158',
        weight: '49',
        nationality: 'Chinese',
        religion: 'Buddhist',
        education_level: 'High School',
    },
    {
        id: 16,
        name: 'Puspita Dewi',
        date_of_birth: '1999-09-29',
        place_of_birth: 'Yogyakarta',
        height: '155',
        weight: '48',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 17,
        name: 'Thandar Win',
        date_of_birth: '1996-05-11',
        place_of_birth: 'Mandalay',
        height: '157',
        weight: '51',
        nationality: 'Burmese',
        religion: 'Buddhist',
        education_level: 'Middle School',
    },
    {
        id: 18,
        name: 'Mary Grace Santos',
        date_of_birth: '1998-11-23',
        place_of_birth: 'Davao',
        height: '162',
        weight: '55',
        nationality: 'Filipino',
        religion: 'Christian',
        education_level: 'College',
    },
    {
        id: 19,
        name: 'Ratna Sari',
        date_of_birth: '1997-01-28',
        place_of_birth: 'Palembang',
        height: '159',
        weight: '53',
        nationality: 'Indonesian',
        religion: 'Islam',
        education_level: 'High School',
    },
    {
        id: 20,
        name: 'Chen Yu',
        date_of_birth: '1995-08-05',
        place_of_birth: 'Beijing',
        height: '160',
        weight: '52',
        nationality: 'Chinese',
        religion: 'Buddhist',
        education_level: 'College',
    },
];

export const dataNationalities = [
    { value: 'Indonesian', label: 'Indonesian' },
    { value: 'Filipino', label: 'Filipino' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Vietnamese', label: 'Vietnamese' },
    { value: 'Burmese', label: 'Burmese' },
    { value: 'Indian', label: 'Indian' },
    { value: 'Malaysian', label: 'Malaysian' },
];

export const dataReligions = [
    { value: 'Islam', label: 'Islam' },
    { value: 'Christian', label: 'Christian' },
    { value: 'Buddhist', label: 'Buddhist' },
    { value: 'Hindu', label: 'Hindu' },
];

export const dataEducationLevels = [
    { value: 'Middle School', label: 'Middle School' },
    { value: 'High School', label: 'High School' },
    { value: 'College', label: 'College' },
];
