export type schemaUser = {
    id: number;
    name: string;
    email: string;
    role: string;
};

export const dataUser: schemaUser[] = [
    { id: 1, name: 'Alice', email: 'alice1@example.com', role: 'admin' },
    { id: 2, name: 'Bob', email: 'bob2@example.com', role: 'sales' },
    { id: 3, name: 'Charlie', email: 'charlie3@example.com', role: 'customer' },
    { id: 4, name: 'David', email: 'david4@example.com', role: 'supplier' },
    { id: 5, name: 'Eve', email: 'eve5@example.com', role: 'admin' },
    { id: 6, name: 'Frank', email: 'frank6@example.com', role: 'sales' },
    { id: 7, name: 'Grace', email: 'grace7@example.com', role: 'customer' },
    { id: 8, name: 'Heidi', email: 'heidi8@example.com', role: 'supplier' },
    { id: 9, name: 'Ivan', email: 'ivan9@example.com', role: 'admin' },
    { id: 10, name: 'Judy', email: 'judy10@example.com', role: 'sales' },
    { id: 11, name: 'Karl', email: 'karl11@example.com', role: 'customer' },
    { id: 12, name: 'Leo', email: 'leo12@example.com', role: 'supplier' },
    { id: 13, name: 'Mona', email: 'mona13@example.com', role: 'admin' },
    { id: 14, name: 'Nina', email: 'nina14@example.com', role: 'sales' },
    { id: 15, name: 'Oscar', email: 'oscar15@example.com', role: 'customer' },
    { id: 16, name: 'Paul', email: 'paul16@example.com', role: 'supplier' },
    { id: 17, name: 'Quinn', email: 'quinn17@example.com', role: 'admin' },
    { id: 18, name: 'Rachel', email: 'rachel18@example.com', role: 'sales' },
    { id: 19, name: 'Sam', email: 'sam19@example.com', role: 'customer' },
    { id: 20, name: 'Tina', email: 'tina20@example.com', role: 'supplier' },
    { id: 21, name: 'Uma', email: 'uma21@example.com', role: 'admin' },
    { id: 22, name: 'Victor', email: 'victor22@example.com', role: 'sales' },
    { id: 23, name: 'Wendy', email: 'wendy23@example.com', role: 'customer' },
    { id: 24, name: 'Xander', email: 'xander24@example.com', role: 'supplier' },
    { id: 25, name: 'Yara', email: 'yara25@example.com', role: 'admin' },
    { id: 26, name: 'Zane', email: 'zane26@example.com', role: 'sales' },
    { id: 27, name: 'Aiden', email: 'aiden27@example.com', role: 'customer' },
    { id: 28, name: 'Bella', email: 'bella28@example.com', role: 'supplier' },
    { id: 29, name: 'Cody', email: 'cody29@example.com', role: 'admin' },
    { id: 30, name: 'Diana', email: 'diana30@example.com', role: 'sales' },
    { id: 31, name: 'Ethan', email: 'ethan31@example.com', role: 'customer' },
    { id: 32, name: 'Fiona', email: 'fiona32@example.com', role: 'supplier' },
    { id: 33, name: 'George', email: 'george33@example.com', role: 'admin' },
    { id: 34, name: 'Holly', email: 'holly34@example.com', role: 'sales' },
    { id: 35, name: 'Ian', email: 'ian35@example.com', role: 'customer' },
    {
        id: 36,
        name: 'Jasmine',
        email: 'jasmine36@example.com',
        role: 'supplier',
    },
    { id: 37, name: 'Kevin', email: 'kevin37@example.com', role: 'admin' },
    { id: 38, name: 'Lily', email: 'lily38@example.com', role: 'sales' },
    { id: 39, name: 'Mason', email: 'mason39@example.com', role: 'customer' },
    { id: 40, name: 'Nora', email: 'nora40@example.com', role: 'supplier' },
    { id: 41, name: 'Owen', email: 'owen41@example.com', role: 'admin' },
    { id: 42, name: 'Piper', email: 'piper42@example.com', role: 'sales' },
    { id: 43, name: 'Quincy', email: 'quincy43@example.com', role: 'customer' },
    { id: 44, name: 'Ruby', email: 'ruby44@example.com', role: 'supplier' },
    { id: 45, name: 'Sean', email: 'sean45@example.com', role: 'admin' },
    { id: 46, name: 'Tara', email: 'tara46@example.com', role: 'sales' },
    { id: 47, name: 'Umar', email: 'umar47@example.com', role: 'customer' },
    { id: 48, name: 'Vera', email: 'vera48@example.com', role: 'supplier' },
    { id: 49, name: 'Will', email: 'will49@example.com', role: 'admin' },
    { id: 50, name: 'Xenia', email: 'xenia50@example.com', role: 'sales' },
    { id: 51, name: 'Yusuf', email: 'yusuf51@example.com', role: 'customer' },
    { id: 52, name: 'Zara', email: 'zara52@example.com', role: 'supplier' },
    { id: 53, name: 'Aaron', email: 'aaron53@example.com', role: 'admin' },
    { id: 54, name: 'Bianca', email: 'bianca54@example.com', role: 'sales' },
    { id: 55, name: 'Caleb', email: 'caleb55@example.com', role: 'customer' },
    { id: 56, name: 'Daisy', email: 'daisy56@example.com', role: 'supplier' },
    { id: 57, name: 'Eli', email: 'eli57@example.com', role: 'admin' },
    { id: 58, name: 'Faith', email: 'faith58@example.com', role: 'sales' },
    { id: 59, name: 'Gavin', email: 'gavin59@example.com', role: 'customer' },
    { id: 60, name: 'Hannah', email: 'hannah60@example.com', role: 'supplier' },
    { id: 61, name: 'Isaac', email: 'isaac61@example.com', role: 'admin' },
    { id: 62, name: 'Jade', email: 'jade62@example.com', role: 'sales' },
    { id: 63, name: 'Kyle', email: 'kyle63@example.com', role: 'customer' },
    { id: 64, name: 'Laura', email: 'laura64@example.com', role: 'supplier' },
    { id: 65, name: 'Miles', email: 'miles65@example.com', role: 'admin' },
    { id: 66, name: 'Nadia', email: 'nadia66@example.com', role: 'sales' },
    { id: 67, name: 'Omar', email: 'omar67@example.com', role: 'customer' },
    { id: 68, name: 'Paula', email: 'paula68@example.com', role: 'supplier' },
    { id: 69, name: 'Reid', email: 'reid69@example.com', role: 'admin' },
    { id: 70, name: 'Sophie', email: 'sophie70@example.com', role: 'sales' },
    { id: 71, name: 'Trent', email: 'trent71@example.com', role: 'customer' },
    { id: 72, name: 'Ursula', email: 'ursula72@example.com', role: 'supplier' },
    { id: 73, name: 'Victor', email: 'victor73@example.com', role: 'admin' },
    { id: 74, name: 'Willa', email: 'willa74@example.com', role: 'sales' },
    { id: 75, name: 'Xavier', email: 'xavier75@example.com', role: 'customer' },
    { id: 76, name: 'Yara', email: 'yara76@example.com', role: 'supplier' },
    { id: 77, name: 'Zion', email: 'zion77@example.com', role: 'admin' },
    { id: 78, name: 'Amber', email: 'amber78@example.com', role: 'sales' },
    {
        id: 79,
        name: 'Brandon',
        email: 'brandon79@example.com',
        role: 'customer',
    },
    { id: 80, name: 'Clara', email: 'clara80@example.com', role: 'supplier' },
    { id: 81, name: 'Derek', email: 'derek81@example.com', role: 'admin' },
    { id: 82, name: 'Elena', email: 'elena82@example.com', role: 'sales' },
    { id: 83, name: 'Felix', email: 'felix83@example.com', role: 'customer' },
    { id: 84, name: 'Gloria', email: 'gloria84@example.com', role: 'supplier' },
    { id: 85, name: 'Harvey', email: 'harvey85@example.com', role: 'admin' },
    { id: 86, name: 'Isla', email: 'isla86@example.com', role: 'sales' },
    { id: 87, name: 'Jonas', email: 'jonas87@example.com', role: 'customer' },
    { id: 88, name: 'Kara', email: 'kara88@example.com', role: 'supplier' },
    { id: 89, name: 'Liam', email: 'liam89@example.com', role: 'admin' },
    { id: 90, name: 'Maya', email: 'maya90@example.com', role: 'sales' },
    { id: 91, name: 'Noah', email: 'noah91@example.com', role: 'customer' },
    { id: 92, name: 'Olivia', email: 'olivia92@example.com', role: 'supplier' },
    { id: 93, name: 'Peter', email: 'peter93@example.com', role: 'admin' },
    { id: 94, name: 'Queenie', email: 'queenie94@example.com', role: 'sales' },
    { id: 95, name: 'Ryan', email: 'ryan95@example.com', role: 'customer' },
    { id: 96, name: 'Sophia', email: 'sophia96@example.com', role: 'supplier' },
    { id: 97, name: 'Thomas', email: 'thomas97@example.com', role: 'admin' },
    { id: 98, name: 'Uma', email: 'uma98@example.com', role: 'sales' },
    { id: 99, name: 'Violet', email: 'violet99@example.com', role: 'customer' },
    { id: 100, name: 'Wyatt', email: 'wyatt100@example.com', role: 'supplier' },
];

export const dataRoles = [
    {
        value: 'admin',
        label: 'Admin',
    },
    {
        value: 'sales',
        label: 'Sales',
    },
    {
        value: 'customer',
        label: 'Customer',
    },
    {
        value: 'supplier',
        label: 'Supplier',
    },
];
